### ISSUE TITLE
Error encrypting zipped tarballs

### ISSUE THREAD

**Issue by adrowe1** [jeroenooms/gpg#4] opened 2018-06-20 19:03 UTC
For reasons beyond my control, I'm trying to preserve directory structures while sending many asymmetrically encrypted datasets to an external API from R on Windows.

I figured the best solution here was to tar/zip parent directories, encrypt using `gpg::gpg_encrypt()`, then POST to the API.

A near-complete reprex is shown here - needing only a public key fingerprint to be usable.
```r
library(gpg)
# make a demo directory to compress and encrypt.
dir.create("test_dir")
writeLines(paste0(rep("aaa\n", 10), collapse=""), "test_dir/test1.txt")
writeLines(paste0(rep("bbb\n", 20), collapse=""), "test_dir/test2.txt")
tar("test_dir.tar.gz", "test_dir", compression = "gzip")

# encrypt file
publicKeyFingerprint <- # Choose a fingerprint you own so you can test decryption
encrypted <- gpg_encrypt("test_dir.tar.gz", publicKeyFingerprint)
writeLines(encrypted, "test_dir.tar.gz.gpg")

# try to decrypt
gpg_decrypt("test_dir.tar.gz.gpg")
```

For some reason there is an issue with the encrypted output, meaning it cannot be decrypted, and I get the following error message.  
`Error in gpg_decrypt("test_dir.tar.gz.gpg") : 
  embedded nul in string:   '\037\x8b\b\0\0\0\0\0\0\003\xed\xd4 ... \xe6?\xbc\0015x)\r\0\f\0\0'`  

I also notice that the encrypted data is always far smaller than should be expected for larger files.  

Is there something obvious I'm doing wrong?  

I tried a similar strategy replacing asymmetrical encryption by `gpg::gpg_encrypt()` with symmetrical using `crypt::encrypt()` and this worked fine, but it's nowhere near as elegant a solution as `gpg_encrypt()` could be if it works.

Do you have any suggestions to solve this issue?

Thanks a lot!

_Error occurs on R v3.5.0 on OSX, with gpg v0.5 from CRAN._

**Comment by jeroen** [comment] 2018-12-29 12:40
Duplicate of https://github.com/jeroen/gpg/issues/5: I was assuming text input, the new version has support for binary data.

**Closed as completed** 2018-12-29 12:59 UTC
